- name: debug txt record to cloudflare
  debug:
    msg:  "{{ opendkim_keys_folder }}/{{ item.name }}"
  with_flattened:
     - "{{ opendkim_domains }}"
  when: ( item.state is defined and item.state != 'absent' ) or ( item.state is undefined and opendkim_domain_state != 'absent' ) and ( opendkim_cf | bool )
  tags:
    - never
    - debug

- name: insert txt record to cloudflare
  shell: echo "{{ opendkim_keys_folder}}/{{ item.name }}/{{ item.selector | default(opendkim_domain_selector) }}.txt"
  register: "files_matched"
  with_flattened:
     - "{{ opendkim_domains }}"
  when: ( item.state is defined and item.state != 'absent' ) or ( item.state is undefined and opendkim_domain_state != 'absent' ) and ( opendkim_cf | bool )
 
- name: debug files
  debug:
    msg: "{{ files_matched }}"   
  tags:
    - never
    - debug   

- name: loop through keys
  include_tasks: cf_selector_record.yml
  with_flattened: "{{ files_matched.results }}"
  when: (item.changed and  opendkim_cf | bool)
