---

- name: preporcess txt record
  debug:
    msg: "{{ item }}"
  tags:
    - debug
    - never

- set_fact:
    tmp_domain: "{{ item.stdout | regex_replace( opendkim_keys_folder , '') }}"

- name: debug domain
  debug: msg={{ tmp_domain }}
  tags:
    - debug
    - never

- set_fact:
    the_domain: "{{ tmp_domain.split('/')[1] | lower }}"

- name: prepare TXT record selector
  shell: cat "{{ item.stdout }}" | cut -f1
  register: record_selector

- name: debug domain selector
  debug:
    msg: "{{ record_selector.stdout_lines }}"
  tags:
    - debug
    - never
- name: prerepare TXT record value
  shell: |
    set -o pipefail
    cat "{{ item.stdout }}" | tr -d '\n[:space:]' | sed s#^.*\(\"## | sed s#\"\).*## | tr -d '"'

  args:
    executable: /bin/bash
  register: record_value

- name: debug the domain
  debug:
    msg: "{{ the_domain }}"
  tags:
    - debug
    - never

- name: debug record_value.stdout
  debug:
    msg: "{{ record_value.stdout }}"
  tags:
    - debug
    - never

- name: update TXT record in Cloudflare
  cloudflare_dns:
    account_email: "{{ opendkim_cf_mail }}"
    account_api_token: "{{ opendkim_cf_api_token }}"
    zone: "{{ the_domain }}"
    record: "{{ record_selector.stdout }}"
    value:  "{{ record_value.stdout }}"
    type: TXT
    state: present
    solo: yes
